# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-30 14:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_category_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
